const MT={en:{back:'Back to NILEX ↗',home:'Home',mailK:'NILEX MAIL',mailTitle:'Send your request to Admin.',mailIntro:'Create your NILEX account, then send your project request directly to the Admin.',loginTab:'Login',signupTab:'Create Email',username:'Username',password:'Password',login:'Login ↗',chooseUser:'Choose username',choosePass:'Choose password',confirmPass:'Confirm password',create:'Create Email ↗',demoNote:'Prototype mode: accounts and messages are saved only in this browser.',logout:'Log out',compose:'+ Compose',inbox:'Inbox',sent:'Sent',localOnly:'Local NILEX account',refresh:'Refresh',newMessage:'New message',cancel:'Cancel',to:'To',subject:'Subject',body:'Message',sendMail:'Send Mail ↗',emptyInbox:'Your inbox is empty.',emptySent:'No sent messages yet.',badLogin:'Username or password is incorrect.',exists:'This username already exists.',created:'Email created. You are now logged in.',passMismatch:'Passwords do not match.',invalidUser:'Use only letters, numbers, dots, underscores or hyphens.',selfMail:'You cannot send a message to yourself.',notFound:'This NILEX user does not exist.',sentOk:'Message sent successfully.',from:'From',you:'You'},ar:{back:'العودة إلى NILEX ↗',home:'الرئيسية',mailK:'NILEX MAIL',mailTitle:'إرسال طلبك للأدمن',mailIntro:'أنشئ إيميل NILEX الخاص بك، وبعدها ابعت طلب مشروعك مباشرة للأدمن.',loginTab:'تسجيل الدخول',signupTab:'إنشاء إيميل',username:'اسم المستخدم',password:'كلمة المرور',login:'دخول ↗',chooseUser:'اختر اسم المستخدم',choosePass:'اختر كلمة المرور',confirmPass:'تأكيد كلمة المرور',create:'إنشاء الإيميل ↗',demoNote:'وضع تجريبي: الحسابات والرسائل محفوظة على هذا المتصفح فقط.',logout:'تسجيل الخروج',compose:'+ رسالة جديدة',inbox:'الوارد',sent:'المرسل',localOnly:'حساب NILEX محلي',refresh:'تحديث',newMessage:'رسالة جديدة',cancel:'إلغاء',to:'إلى',subject:'الموضوع',body:'الرسالة',sendMail:'إرسال الرسالة ↗',emptyInbox:'مفيش رسائل في الوارد.',emptySent:'مفيش رسائل مرسلة لسه.',badLogin:'اسم المستخدم أو كلمة المرور غلط.',exists:'اسم المستخدم ده موجود بالفعل.',created:'تم إنشاء الإيميل وتسجيل الدخول.',passMismatch:'كلمتا المرور غير متطابقتين.',invalidUser:'استخدم حروف وأرقام ونقطة أو _ أو - فقط.',selfMail:'مينفعش تبعت لنفسك.',notFound:'مستخدم NILEX ده مش موجود.',sentOk:'تم إرسال الرسالة بنجاح.',from:'من',you:'أنت'}};
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);let lang=localStorage.getItem('nilexLang')||'en';let currentFolder='inbox';
function db(){return JSON.parse(localStorage.getItem('nilexMailDB')||'{"users":{},"messages":[]}')}
function saveDB(x){localStorage.setItem('nilexMailDB',JSON.stringify(x))}
function t(k){return MT[lang][k]||k}
function ensureAdmin(){const d=db();if(!d.users.admin){d.users.admin={password:'admin123',name:'Admin',admin:true};saveDB(d)}}
function applyLang(){document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.body.classList.toggle('rtl',lang==='ar');$$('[data-i18n]').forEach(e=>e.textContent=t(e.dataset.i18n));$('#lang').textContent=lang==='ar'?'English':'العربية';renderApp()}
$('#lang').onclick=()=>{lang=lang==='en'?'ar':'en';localStorage.setItem('nilexLang',lang);applyLang()};
$$('.auth-tabs button').forEach(b=>b.onclick=()=>{$$('.auth-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#loginForm').classList.toggle('hidden',b.dataset.tab!=='login');$('#signupForm').classList.toggle('hidden',b.dataset.tab!=='signup')});
$('#signupUser').oninput=()=>$('#previewUser').textContent=$('#signupUser').value.toLowerCase().replace(/[^a-z0-9._-]/g,'');
$('#signupForm').onsubmit=e=>{e.preventDefault();let u=$('#signupUser').value.trim().toLowerCase(),p=$('#signupPass').value,p2=$('#signupPass2').value,note=$('#signupNote');if(!/^[a-z0-9._-]{3,24}$/.test(u)){note.textContent=t('invalidUser');return}if(u==='admin'){note.textContent=t('exists');return}if(p!==p2){note.textContent=t('passMismatch');return}let d=db();if(d.users[u]){note.textContent=t('exists');return}d.users[u]={password:p};saveDB(d);localStorage.setItem('nilexMailCurrent',u);note.textContent=t('created');setTimeout(showApp,250)};
$('#loginForm').onsubmit=e=>{e.preventDefault();let u=$('#loginUser').value.trim().toLowerCase(),p=$('#loginPass').value,d=db();if(!d.users[u]||d.users[u].password!==p){$('#loginNote').textContent=t('badLogin');return}localStorage.setItem('nilexMailCurrent',u);showApp()};
function showApp(){$('#auth').classList.add('hidden');$('#mailApp').classList.remove('hidden');renderApp()}
function logout(){localStorage.removeItem('nilexMailCurrent');$('#mailApp').classList.add('hidden');$('#auth').classList.remove('hidden');$('#loginForm').reset();$('#signupForm').reset();$('#signupNote').textContent='';$('#loginNote').textContent=''}
$('#logout').onclick=logout;
function renderApp(){let u=localStorage.getItem('nilexMailCurrent');if(!u)return;$('#accountTitle').textContent=u+'@nilex';let d=db();let msgs=d.messages.filter(m=>currentFolder==='inbox'?m.to===u:m.from===u);$('#folderTitle').textContent=currentFolder==='inbox'?t('inbox'):t('sent');let unread=d.messages.filter(m=>m.to===u&&!m.read).length;$('#inboxCount').textContent=unread;let list=$('#messageList');if(!msgs.length){list.innerHTML='<div class="empty">'+(currentFolder==='inbox'?t('emptyInbox'):t('emptySent'))+'</div>';return}list.innerHTML=msgs.slice().reverse().map(m=>`<article class="message ${m.to===u&&!m.read?'unread':''}" data-id="${m.id}"><div class="message-main"><div><div class="message-from">${m.from===u?t('you'):escapeHtml(m.from+'@nilex')}</div><div class="message-subject">${escapeHtml(m.subject)}</div><div class="message-preview">${escapeHtml(m.body)}</div></div><div class="message-date">${new Date(m.date).toLocaleString(lang==='ar'?'ar-EG':'en-US')}</div></div></article>`).join('');$$('.message').forEach(el=>el.onclick=()=>openMessage(el.dataset.id))}
function openMessage(id){let d=db(),m=d.messages.find(x=>x.id===id),u=localStorage.getItem('nilexMailCurrent');if(!m)return;if(m.to===u)m.read=true;saveDB(d);alert((m.from===u?t('you'):m.from+'@nilex')+'\n\n'+m.subject+'\n\n'+m.body);renderApp()}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
$$('.folder').forEach(b=>b.onclick=()=>{currentFolder=b.dataset.folder;$$('.folder').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#composeView').classList.add('hidden');$('#listView').classList.remove('hidden');renderApp()});$('#refresh').onclick=renderApp;
$('#compose').onclick=()=>{$('#listView').classList.add('hidden');$('#composeView').classList.remove('hidden');$('#sendNote').textContent=''};$('#cancelCompose').onclick=()=>{$('#composeView').classList.add('hidden');$('#listView').classList.remove('hidden');$('#composeForm').reset();$('#toUser').value='admin@nilex'};
$('#composeForm').onsubmit=e=>{e.preventDefault();let u=localStorage.getItem('nilexMailCurrent'),to='admin',d=db();if(u==='admin'){to=$('#toUser').value.trim().toLowerCase().replace(/@nilex$/,'')}if(to===u){$('#sendNote').textContent=t('selfMail');return}if(!d.users[to]){$('#sendNote').textContent=t('notFound');return}d.messages.push({id:Date.now().toString(36)+Math.random().toString(36).slice(2),from:u,to,subject:$('#subject').value.trim(),body:$('#body').value.trim(),date:new Date().toISOString(),read:false});saveDB(d);$('#sendNote').textContent=t('sentOk');$('#composeForm').reset();$('#toUser').value='admin@nilex';setTimeout(()=>{$('#composeView').classList.add('hidden');$('#listView').classList.remove('hidden');currentFolder='sent';$$('.folder').forEach(x=>x.classList.toggle('active',x.dataset.folder==='sent'));renderApp()},500)};
ensureAdmin();if(localStorage.getItem('nilexMailCurrent'))showApp();applyLang();
