const SUPABASE_URL="https://loqwcsxdqgasgokfmswi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY="sb_publishable_vkNXRSYz-hz_PxJCXGwdhg__0-Jmlsx";
const supabaseClient=supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}});
let currentUser=null,currentProfile=null,adminUser=null,currentFolder="inbox",openedMessage=null,adminMode=false;
const $=id=>document.getElementById(id);
const params=new URLSearchParams(location.search);
function internal(p){return p?.internal_email||`${p?.username||""}@nilex`}
function display(p){return p?.display_name||p?.username||"User"}
function toast(t){const e=$("mailToast");if(!e){alert(t);return}e.textContent=t;e.classList.add("show");clearTimeout(window.tt);window.tt=setTimeout(()=>e.classList.remove("show"),2200)}
function show(id){if($(id))$(id).style.display=""} function hide(id){if($(id))$(id).style.display="none"}

async function loadProfile(){const {data,error}=await supabaseClient.from("profiles").select("id,username,email,internal_email,display_name,role,created_at").eq("id",currentUser.id).single();if(error)throw error;currentProfile=data;$("accountName").textContent=display(data);$("accountEmail").textContent=internal(data);$("adminControls").style.display=data.role==="admin"?"":"none"}
async function loadAdmin(){const {data,error}=await supabaseClient.from("profiles").select("id,username,display_name,internal_email").eq("role","admin").limit(1).maybeSingle();if(error)throw error;adminUser=data}
async function loadAdminReceivers(){if(currentProfile?.role!=="admin")return;const {data,error}=await supabaseClient.from("profiles").select("id,username,display_name,internal_email,role").neq("id",currentUser.id).order("username",{ascending:true});if(error){console.error(error);toast("تعذر تحميل الحسابات: "+error.message);return}const s=$("adminReceiver");s.innerHTML='<option value="">اختر الحساب</option>';(data||[]).forEach(p=>{const o=document.createElement("option");o.value=p.id;o.textContent=`${display(p)} — ${internal(p)}`;s.appendChild(o)})}

async function startApp(){hide("loginView");hide("signupView");show("mailApp");try{await loadProfile();await loadAdmin();await loadAdminReceivers();const service=params.get("service");if(params.get("compose")==="1"){openCompose(false);if(service){const select=$("messageSubject");const option=[...select.options].find(o=>o.value===service||o.textContent===service);if(option)select.value=option.value;else{const o=document.createElement("option");o.value=service;o.textContent=service;select.appendChild(o);select.value=service}}}else await loadMessages()}catch(e){console.error(e);toast(e.message||"حدث خطأ")}}

async function login(){const u=$("loginUsername").value.trim(),p=$("loginPassword").value;if(!u||!p)return toast("اكتب اسم المستخدم وكلمة المرور");let email=u;if(!email.includes("@"))email+="@nilex.local";else if(email.endsWith("@nilex"))email=email.replace("@nilex","@nilex.local");const {data,error}=await supabaseClient.auth.signInWithPassword({email,password:p});if(error)return toast(error.message);currentUser=data.user;await startApp()}
async function signup(){const username=$("signupUsername").value.trim(),password=$("signupPassword").value;if(!username||!password)return toast("أدخل البيانات المطلوبة");const r=await fetch(`${SUPABASE_URL}/functions/v1/bright-service`,{method:"POST",headers:{"Content-Type":"application/json","apikey":SUPABASE_PUBLISHABLE_KEY},body:JSON.stringify({username,password})});let j={};try{j=await r.json()}catch{}if(!r.ok||!j.success)return toast(j.error||"فشل إنشاء الحساب");const {data,error}=await supabaseClient.auth.signInWithPassword({email:`${username}@nilex.local`,password});if(error)return toast(error.message);currentUser=data.user;await startApp()}

function openCompose(admin=false){adminMode=admin;hide("messageView");hide("messagesList");show("composeView");$("adminRecipientBox").style.display=admin?"":"none";$("normalRecipientBox").style.display=admin?"none":"";$("adminSubjectBox").style.display=admin?"":"none";$("serviceLabel").style.display=admin?"none":"";$("messageSubject").style.display=admin?"none":"";$("messageBody").value="";if(admin)$("adminSubject").value="";if(!admin)$("messageSubject").value="";$("composeError").textContent=""}
async function openReply(){if(!openedMessage)return;const isAdmin=currentProfile.role==="admin";openCompose(isAdmin);if(isAdmin){await loadAdminReceivers();$("adminReceiver").value=openedMessage.sender_id;$("adminSubject").value=openedMessage.subject?.startsWith("رد:")?openedMessage.subject:`رد: ${openedMessage.subject||""}`}else{$("messageSubject").value=openedMessage.subject?.startsWith("رد:")?openedMessage.subject:`رد: ${openedMessage.subject||""}`}$("messageBody").focus()}

async function openMessage(id){const {data,error}=await supabaseClient.from("messages").select("id,sender_id,receiver_id,subject,body,is_read,created_at").eq("id",id).single();if(error)return toast(error.message);openedMessage=data;hide("messagesList");hide("composeView");show("messageView");$("viewSubject").textContent=data.subject||"(بدون عنوان)";$("viewDate").textContent=new Date(data.created_at).toLocaleString("ar-EG");const {data:sp}=await supabaseClient.from("profiles").select("id,username,display_name,internal_email,role").eq("id",data.sender_id).maybeSingle();const {data:rp}=await supabaseClient.from("profiles").select("id,username,display_name,internal_email,role").eq("id",data.receiver_id).maybeSingle();$("viewFrom").textContent=`من: ${display(sp)} — ${internal(sp)}`;$("viewTo").textContent=`إلى: ${display(rp)} — ${internal(rp)}`;$("viewBody").textContent=data.body;$("replyMessageBtn").style.display=data.receiver_id===currentUser.id?"":"none";if(data.receiver_id===currentUser.id&&!data.is_read)await supabaseClient.from("messages").update({is_read:true}).eq("id",id).eq("receiver_id",currentUser.id)}

async function loadMessages(){const field=currentFolder==="sent"?"sender_id":"receiver_id";const {data,error}=await supabaseClient.from("messages").select("id,sender_id,receiver_id,subject,body,is_read,created_at").eq(field,currentUser.id).order("created_at",{ascending:false});if(error)return toast(error.message);hide("messageView");hide("composeView");show("messagesList");const list=$("messagesList");list.innerHTML="";if(!data?.length){list.innerHTML='<div class="empty">لا توجد رسائل حاليًا</div>';return}const ids=[...new Set(data.flatMap(m=>[m.sender_id,m.receiver_id]))];const {data:profiles}=await supabaseClient.from("profiles").select("id,username,display_name,internal_email,role").in("id",ids);const map=new Map((profiles||[]).map(p=>[p.id,p]));data.forEach(m=>{const other=map.get(currentFolder==="sent"?m.receiver_id:m.sender_id);const row=document.createElement("button");row.className="message-row"+(!m.is_read&&currentFolder==="inbox"?" unread":"");row.innerHTML=`<div class="message-dot"></div><div class="message-main"><strong>${esc(m.subject||"(بدون عنوان)")}</strong><span>${esc(display(other))} — ${esc(internal(other))}</span><p>${esc((m.body||"").slice(0,110))}</p></div><time>${new Date(m.created_at).toLocaleDateString("ar-EG")}</time>`;row.onclick=()=>openMessage(m.id);list.appendChild(row)})}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}

async function sendMessage(){const body=$("messageBody").value.trim();if(!body)return toast("اكتب نص الرسالة");let receiverId,subject;if(adminMode){receiverId=$("adminReceiver").value;subject=$("adminSubject").value.trim()}else{receiverId=adminUser?.id;subject=$("messageSubject").value}if(!receiverId)return toast("اختر الحساب");if(!subject)subject="رسالة جديدة";const {error}=await supabaseClient.from("messages").insert({sender_id:currentUser.id,receiver_id:receiverId,subject,body,is_read:false});if(error)return toast(error.message);toast("تم إرسال الرسالة ✓");await loadMessages()}

$("loginButton").onclick=login;$("signupButton").onclick=signup;$("showSignup").onclick=()=>{hide("loginView");show("signupView")};$("showLogin").onclick=()=>{hide("signupView");show("loginView")};$("newMessageBtn").onclick=()=>openCompose(false);$("adminComposeBtn").onclick=()=>openCompose(true);$("sendButton").onclick=sendMessage;$("replyMessageBtn").onclick=openReply;$("backToListBtn").onclick=loadMessages;$("cancelComposeBtn").onclick=loadMessages;
$("inboxFolder").onclick=async()=>{currentFolder="inbox";$("inboxFolder").classList.add("active");$("sentFolder").classList.remove("active");await loadMessages()};
$("sentFolder").onclick=async()=>{currentFolder="sent";$("sentFolder").classList.add("active");$("inboxFolder").classList.remove("active");await loadMessages()};
$("logoutButton").onclick=async()=>{await supabaseClient.auth.signOut();location.href="mail.html"};$("signupUsername").oninput=e=>$("signupEmail").value=e.target.value.trim()+"@nilex";
supabaseClient.auth.onAuthStateChange((event,session)=>{if(session&&event==="SIGNED_IN"){currentUser=session.user;setTimeout(startApp,0)}});
(async()=>{const {data}=await supabaseClient.auth.getSession();if(data.session){currentUser=data.session.user;await startApp()}else{show("loginView");hide("signupView");hide("mailApp")}})();