const SUPABASE_URL="https://loqwcsxdqgasgokfmswi.supabase.co";const SUPABASE_PUBLISHABLE_KEY="sb_publishable_vkNXRSYz-hz_PxJCXGwdhg__0-Jmlsx";const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);const $=id=>document.getElementById(id);let user=null,profile=null,folder="inbox",messages=[];
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));const uname=p=>p?.display_name||p?.username||p?.email||"مستخدم";const email=p=>p?.email?.replace("@nilex.local","@nilex")||"";const err=(id,t="")=>{$(id).textContent=t;$(id).style.display=t?"block":"none"};function screen(id){["loginScreen","registerScreen","mailScreen"].forEach(x=>$(x).style.display=x===id?(x==="mailScreen"?"block":"flex"):"none")}
async function login(){err("loginError");let v=$("loginUsername").value.trim().toLowerCase(),pass=$("loginPassword").value;if(!v||!pass)return err("loginError","اكتب اسم المستخدم وكلمة المرور.");let em=v.includes("@")?(v.endsWith("@nilex")?v.replace("@nilex","@nilex.local"):v):v+"@nilex.local";let b=$("loginBtn");b.disabled=true;b.textContent="جاري الدخول...";try{let r=await db.auth.signInWithPassword({email:em,password:pass});if(r.error||!r.data.user)return err("loginError","اسم المستخدم أو كلمة المرور غلط.");user=r.data.user;await loadProfile();if(!profile){await db.auth.signOut();return err("loginError","بيانات الحساب غير موجودة.")}screen("mailScreen");await init()}catch(e){console.error(e);err("loginError","حصل خطأ أثناء تسجيل الدخول.")}finally{b.disabled=false;b.textContent="تسجيل الدخول"}}
async function register(){err("registerError");let u=$("registerUsername").value.trim().toLowerCase(),d=$("registerDisplayName").value.trim(),p=$("registerPassword").value;if(!/^[a-z0-9._-]{3,30}$/.test(u))return err("registerError","اسم المستخدم يجب أن يكون 3-30 حرفًا بالإنجليزية والأرقام و . _ - فقط.");if(!d||p.length<6)return err("registerError","اكتب الاسم وكلمة مرور 6 أحرف على الأقل.");let em=u+"@nilex.local",b=$("registerBtn");b.disabled=true;try{let r=await db.auth.signUp({email:em,password:p});if(r.error)return err("registerError",r.error.message);if(!r.data.session)return err("registerError","الحساب اتعمل لكن تأكيد البريد مفعّل في Supabase؛ عطّله للدخول مباشرة.");let q=await db.from("profiles").insert({id:r.data.user.id,username:u,email:em,display_name:d,role:"user"});if(q.error)return err("registerError","تعذر إنشاء بيانات الحساب.");user=r.data.user;await loadProfile();screen("mailScreen");await init()}finally{b.disabled=false}}
async function loadProfile(){let r=await db.from("profiles").select("id,username,email,display_name,role").eq("id",user.id).maybeSingle();if(r.error)console.error(r.error);profile=r.data}async function admin(){let r=await db.from("profiles").select("id,username,email,display_name,role").eq("role","admin").limit(1).maybeSingle();return r.data}async function recipient(v){v=v.trim().toLowerCase();if(!v)return null;let r;if(v.includes("@")){if(v.endsWith("@nilex"))v=v.replace("@nilex","@nilex.local");r=await db.from("profiles").select("id,username,email,display_name,role").eq("email",v).maybeSingle()}else r=await db.from("profiles").select("id,username,email,display_name,role").eq("username",v).maybeSingle();return r.data}
const select=`id,sender_id,receiver_id,subject,body,is_read,created_at,sender:profiles!messages_sender_id_fkey(id,username,email,display_name),receiver:profiles!messages_receiver_id_fkey(id,username,email,display_name)`;
async function load(){let q=db.from("messages").select(select).order("created_at",{ascending:false});q=folder==="inbox"?q.eq("receiver_id",user.id):q.eq("sender_id",user.id);let r=await q;if(r.error){console.error(r.error);$("messagesList").innerHTML='<div class="empty">حصل خطأ أثناء تحميل الرسائل.</div>';return}messages=r.data||[];render();count()}
function render(){if(!messages.length){$("messagesList").innerHTML='<div class="empty">مفيش رسائل هنا.</div>';return}$("messagesList").innerHTML=messages.map(m=>{let p=folder==="inbox"?m.sender:m.receiver;return `<button class="row" data-id="${m.id}"><div class="avatar">${esc(uname(p)[0])}</div><div class="rowbody"><div class="rowtop"><strong>${esc(uname(p))}</strong><span class="muted">${new Date(m.created_at).toLocaleString("ar-EG")}</span></div><div class="muted">${esc(email(p))}</div><b>${esc(m.subject||"بدون عنوان")}</b><div class="preview">${esc(m.body)}</div></div></button>`}).join("");document.querySelectorAll(".row").forEach(x=>x.onclick=()=>open(+x.dataset.id))}
async function open(id){let m=messages.find(x=>+x.id===id);if(!m)return;if(folder==="inbox"&&!m.is_read){await db.from("messages").update({is_read:true}).eq("id",id);m.is_read=true}$("listView").style.display="none";$("messageView").style.display="block";$("messageContent").innerHTML=`<div><button class="mini" onclick="back()">→ رجوع</button><div class="message-head"><h2>${esc(m.subject||"بدون عنوان")}</h2><div class="muted">${esc(uname(m.sender))} — ${esc(email(m.sender))}</div></div><div class="message-body">${esc(m.body).replace(/\n/g,"<br>")}</div></div>`;count()}
function back(){$("messageView").style.display="none";$('listView').style.display="block";load()}async function count(){let r=await db.from("messages").select("id",{count:"exact",head:true}).eq("receiver_id",user.id).eq("is_read",false);let n=r.count||0;$("inboxCount").textContent=n;$("inboxCount").style.display=n?"inline":"none"}
function compose(){["listView","messageView"].forEach(x=>$(x).style.display="none");$("composeView").style.display="block";$("composeTitle").textContent=profile.role==="admin"?"رسالة جديدة":"إرسال طلبك للأدمن";$("recipientBox").style.display=profile.role==="admin"?"block":"none";$("recipientInput").disabled=profile.role!=="admin";$("recipientInput").value=profile.role==="admin"?"":"admin@nilex";$("subjectInput").value="";$("bodyInput").value="";err("composeError")}
async function send(){err("composeError");let to=profile.role==="admin"?await recipient($("recipientInput").value):await admin();if(!to)return err("composeError","المستخدم أو حساب الأدمن غير موجود.");let body=$("bodyInput").value.trim();if(!body)return err("composeError","اكتب الرسالة.");let b=$("sendMessageBtn");b.disabled=true;let r=await db.from("messages").insert({sender_id:user.id,receiver_id:to.id,subject:$("subjectInput").value.trim(),body});b.disabled=false;if(r.error){console.error(r.error);return err("composeError","حصل خطأ أثناء الإرسال.")}back()}
async function init(){await loadProfile();if(!profile)return;$("welcomeText").textContent="أهلاً "+uname(profile);$("profileEmail").textContent=email(profile);$("profileAvatar").textContent=uname(profile)[0];$("adminControls").style.display=profile.role==="admin"?"block":"none";change("inbox")}
async function change(f){folder=f;$("folderTitle").textContent=f==="inbox"?"الوارد":"المرسل";document.querySelectorAll(".folder").forEach(x=>x.classList.toggle("active",x.dataset.folder===f));back();await load()}
async function logout(){await db.auth.signOut();user=null;profile=null;screen("loginScreen")}
document.addEventListener("DOMContentLoaded",async()=>{ $("loginBtn").onclick=login;$("showRegisterBtn").onclick=()=>screen("registerScreen");$("backLoginBtn").onclick=()=>screen("loginScreen");$("registerBtn").onclick=register;$("newMessageBtn").onclick=compose;$("adminComposeBtn").onclick=compose;$("cancelComposeBtn").onclick=back;$("sendMessageBtn").onclick=send;$("backToListBtn").onclick=back;$("refreshBtn").onclick=load;$("logoutBtn").onclick=logout;$("homeBtn").onclick=()=>location.href="index.html";document.querySelectorAll(".folder").forEach(x=>x.onclick=()=>change(x.dataset.folder));let s=await db.auth.getSession();if(s.data.session?.user){user=s.data.session.user;await loadProfile();if(profile){screen("mailScreen");await init()}else await logout()}else screen("loginScreen")});
